name: RL-Odyssey
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - gymnasium==1.0.0
  - numpy
  - pandas
  - ipympl
  - matplotlib
  - imageio
  - tensorboard
  - dm-control=1.0.19
  - ipykernel
  - ffmpeg
  - pip:
      - "gymnasium[atari]==1.0.0"
      - "gymnasium[classic_control]"
      - "gymnasium[mujoco]"
      - "pettingzoo[mpe]"
      - "pettingzoo[sisl]"
      - "gymnasium-robotics==1.3.1"
      - supersuit
      - torch
      - opencv-python
      - "imageio[ffmpeg]"
